<?php
/**
 * @file
 * Sets the default group in a new OG Content node.
 */

/**
 * Implements hook_form_alter().
 */
function og_defaultgroup_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form[OG_AUDIENCE_FIELD])) {

    if (isset($form['uid']['#value'])){
      $uid = $form['uid']['#value'];
      $account = user_load($uid);
    } 
    else {
      global $user;
      $account = $user;
    }
    
    $gids = array();
    
    if (!isset($form[OG_AUDIENCE_FIELD]['und']['#default_value']['0'])) {

      $gids = og_get_groups_by_user($account);
      $defaultgroup = og_load_entity_from_group(end($gids));
      $defaultgids = array(end($gids));
      
      foreach ($gids as $key => $val) {
        $group = og_load_entity_from_group($val);
        if (!is_object($group)) {
          continue;
        }
        if ($defaultgroup->changed < $group->changed ) {
          $defaultgroup = $group;
          $defaultgids = array($val);
          
        }
      }
      $form[OG_AUDIENCE_FIELD]['und']['#default_value']= $defaultgids;
    }
     
  }

  return;
}
